Snatch:
  Ghost Mushroom: 20
  Goldthorn: 20
  Gromsblood: 20
  Mountain Silversage: 20
  Oily Blackmouth: 20
  Plaguebloom: 20
  Small Flame Sac: 5
  Stonescale Eel: 20
  Sungrass: 20
  Wild Steelbloom: 20
Commodities:
  Arcane Crystal: 10
  Arcanite Bar: 10
  Elemental Sharpening Stone: 20
  Greater Eternal Essence: 10
  Lesser Eternal Essence: 10
  Essence of Water: 10
  Essence of Undead: 10
  Thorium Bar: 20
Intermediate:
  Blackmouth Oil: 20
  Fire Oil: 20
  Stonescale Oil: 20
Buy:
  Blindweed: 20
  Dream Dust: 20
  Dreamfoil: 20
  Fadeleaf: 20
  Firefin Snapper: 20
  Grave Moss: 20
  Stranglekelp: 20
  Thorium Ore: 10
Sell:
  Arcane Elixir: 5
  Elixir of Fortitude: 5
  Elixir of Giants: 5
  Elixir of Greater Agility: 5
  Elixir of Shadow Power: 5
  Elixir of Superior Defense: 5
  Elixir of the Mongoose: 5
  Fire Protection Potion: 5
  Free Action Potion: 5
  Greater Arcane Protection Potion: 5
  Greater Shadow Protection Potion: 5
  Greater Stoneshield Potion: 5
  Invisibility Potion: 5
  Limited Invulnerability Potion: 5
  Mighty Rage Potion: 5
  Superior Mana Potion: 5
Standards:
  Thistle Tea: 10
  Superior Health Potion: 5
  Major Health Potion: 5
  Dense Sharpening Stones: 20
  Heavy Runecloth Bandage: 20
  Blinding Powder: 20
  Flash Powder: 20
  Instant Poison V: 20
  Crippling Poison II: 20
  Grilled Squid: 20
  Tender Wolf Steak: 20
  Swiftness Potion: 5