Elixir of Greater Defense:
  Wild Steelbloom: 1
  Goldthorn: 1
Arcane Elixir:
  Blindweed: 1
  Goldthorn: 1
Elixir of Fortitude:
  Goldthorn: 1
  Wild Steelbloom: 1
Elixir of Greater Agility:
  Sungrass: 1
  Goldthorn: 1
Limited Invulnerability Potion:
  Blindweed: 2
  Ghost Mushroom: 1
Superior Mana Potion:
  Sungrass: 2
  Blindweed: 2
Elixir of Shadow Power:
  Ghost Mushroom: 3
Invisibility Potion:
  Ghost Mushroom: 1
  Sungrass: 1
Elixir of Giants:
  Sungrass: 1
  Gromsblood: 1
Mighty Rage Potion:
  Gromsblood: 3
Elixir of Superior Defense:
  Stonescale Oil: 2
  Sungrass: 1
Stonescale Oil:
  Stonescale Eel: 1
Greater Stoneshield Potion:
  Stonescale Oil: 3
  Thorium Ore: 1
Shadow Oil:
  Grave Moss: 4
  Fadeleaf: 4
Greater Shadow Protection Potion:
  Shadow Oil: 1
  Dreamfoil: 1
Greater Arcane Protection Potion:
  Dream Dust: 1
  Dreamfoil: 1
Elixir of the Mongoose:
  Mountain Silversage: 2
  Plaguebloom: 2
Fire Protection Potion:
  Small Flame Sac: 1
  Fire Oil: 1
Fire Oil:
  Firefin Snapper: 2
Free Action Potion:
  Blackmouth Oil: 2
  Stranglekelp: 1
Blackmouth Oil:
  Oily Blackmouth: 2
Grilled Squid:
  Winter Squid: 1
Tender Wolf Steak:
  Tender Wolf Meat: 1
# Elixir of Greater Intellect:
#   Blindweed: 1
#   Khadgar's Whiskers: 1  
# Swiftness Potion:
#   Swiftthistle: 1
#   UNKNOWN: 1
# Essence of Water:
#   Essence of Undeath: 1
#   TIME: 24
# Arcanite Bar:
#   Arcane Crystal: 1
#   Thorium Bar: 1
#   TIME: 48
# Superior Healing Potion:
#   UNKNOWN: 1
# Major Healing Potion:
#   UNKNOWN: 1